name: Build and Deploy Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: login to Dockerhub
        uses: azure/docker-login@v1
        with:
          login-server: gcr.io
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: login to GCR
#        uses: azure/docker-login@v1
#        with:
#          login-server: gcr.io
#          username: ${{ secrets.GCR_USERNAME }}
#          password: ${{ secrets.GCR_PASSWORD }}
#      - name: login to docker.io
#        uses: azure/docker-login@v1
#        with:
#          login-server: index.docker.io
#          username: ${{ secrets.DOCKERIO_USERNAME }}
#          password: ${{ secrets.DOCKERIO_PASSWORD }}
      - name: build and push
        run: |
          docker build --tag ge --target ge .
          docker build --tag wemmick .
          docker tag ge beradev/wemmick:ge-0.11.7
          docker tag ge gcr.io/product-id/wemmick:ge-0.11.7
          docker tag wemmick beradev/wemmick:lastest
          docker tag wemmick gcr.io/product-id/wemmick:${{ env.GITHUB_REF }}
          [ $(git rev-parse --abbrev-ref HEAD) == 'main'] && docker images --format "{{.Repository}}:{{.Tag}}" | grep 'beradev' | xargs -n 1 docker push
          docker images --format "{{.Repository}}:{{.Tag}}" | grep 'gcr' | xargs -n 1 docker push
