# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: App Test

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Build gRPC interfaces
        run: |
          cd src && \
            python -m grpc_tools.protoc \
            -I wemmick/protos \
            --python_out=. \
            --grpc_python_out=. \
            wemmick/protos/wemmick/*.proto
      - name: Typecheck with mypy
        run: |
          mypy src/
      - name: Install package
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest tests
